### ISSUE TITLE
Unified Model Configuration with Endpoint Capabilities

### ISSUE THREAD

**Issue by dittops** [BudEcosystem/tensorzero#12]
## Summary

Refactor the model configuration system to use a unified model table with explicit endpoint capabilities, replacing the current separate `models` and `embedding_models` tables.

## Background

Currently, TensorZero uses separate configuration sections for different model types:
- `models` for chat/completion models
- `embedding_models` for embedding models

This leads to configuration duplication when the same model supports multiple endpoints (e.g., vLLM models that support both chat and embeddings).

## Proposed Solution

Introduce an `endpoints` field to model configurations that explicitly declares supported capabilities:

```toml
[models.llama_7b]
routing = ["vllm"]
endpoints = ["chat", "embeddings"]  # Explicitly declare supported endpoints

[models.llama_7b.providers.vllm]
type = "vllm"
model_name = "llama-2-7b-chat"
api_base = "http://localhost:8000"
```

### 1. Add Endpoint Capability Enum
```rust
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum EndpointCapability {
    Chat,
    Embeddings,
    // Future: Completions, Images, Audio, FineTuning, etc.
}
```

### 2. Update Model Configuration
- Add `endpoints: HashSet<EndpointCapability>` to `ModelConfig`
- Default to `["chat"]` for backward compatibility
- Add `supports_endpoint(capability)` method for runtime checks

### 3. Unified Model Table
- Merge `models` and `embedding_models` into single table
- Update all endpoint handlers to check capabilities
- Better error messages when endpoint not supported

### 4. Migration Strategy
- Support both old and new formats during transition
- Log deprecation warnings for `embedding_models` section
- Provide migration guide in documentation

## Benefits

1. **DRY Configuration**: No duplication for multi-capability models
2. **Extensibility**: Easy to add new endpoints (images, audio, fine-tuning, etc.)
3. **Type Safety**: Compile-time guarantees about endpoint support
4. **Clear Capability Model**: Explicit about what each model can do
5. **Future-Proof**: Ready for OpenAI's expanding API surface

### Multi-Modal Models
```toml
[models.gpt_4_vision]
endpoints = ["chat", "images", "embeddings"]
```

### Specialized Models
```toml
[models.whisper]
endpoints = ["audio"]

[models.dall_e]
endpoints = ["images"]
```

## Breaking Changes

- Configuration format change (with migration path)
- API for accessing models would need updates
- Custom integrations may need updates

## Related Work

- PR #11 implemented basic embedding support with separate tables
- This would build on that foundation

## Implementation Checklist

- [ ] Design capability-based model configuration schema
- [ ] Implement `EndpointCapability` enum and model updates
- [ ] Create configuration migration logic
- [ ] Update all endpoint handlers to use unified table
- [ ] Add capability validation in config parsing
- [ ] Update documentation and examples
- [ ] Add comprehensive tests
- [ ] Create migration guide for users

## Future Considerations

This architecture would make it easy to add:
- Completions endpoint (`/v1/completions`)
- Images endpoint (`/v1/images/generations`)
- Audio endpoints (`/v1/audio/*`)
- Fine-tuning endpoints
- Custom endpoints for specialized models

---

Reference: Initial discussion in PR #11 about endpoint capabilities
